apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: dmss
spec:
  environments:
    - name: prod
      build:
        from: release
    - name: dev
      build:
        from: master
  components:
    - name: api
      src: .
      ports:
        - name: flask
          port: 80
      publicPort: flask
      secrets:
        - MONGO_URI
      environmentConfig:
        - environment: dev
          variables:
            ENVIRONMENT: "production"
            FLASK_RUN_PORT: 80
        - environment: prod
          variables:
            ENVIRONMENT: "production"
            FLASK_RUN_PORT: 80
  dnsAppAlias:
    environment: prod
    component: api
