on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  run-tests:
    uses: ./.github/workflows/testing.yml

  publish-latest-docker-image:
    needs: [checks, run-tests]
    uses: ./.github/workflows/publish.yml
    with:
      image-tag: latest
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


