on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  run-tests:
    uses: ./.github/workflows/testing.yml

  publish-latest-docker-image:
    needs: [checks, run-tests]
    uses: ./.github/workflows/publish.yml
    with:
      image-tags: latest
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  release-please:
    needs: [checks, run-tests]
    uses: ./.github/workflows/create-release-pr.yaml

  publish-production-docker-image:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/publish.yml
    with:
      image-tags: production,${{ needs.release-please.outputs.tag_name }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  publish-new-pypi-package:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/publish-to-pypi.yml
    with:
      version: ${{ needs.release-please.outputs.tag_name }}
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
