on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  run-tests:
    uses: ./.github/workflows/testing.yml

  publish-latest-docker-image:
    needs: [checks, run-tests]
    uses: ./.github/workflows/publish.yml
    with:
      image-tag: latest
    secrets: ${{ secrets.DOCKER_PASSWORD }}


  publish-new-pypi-package:
    needs: [checks, run-tests]
    uses: ./.github/workflows/publish-to-pypi.yml
    secrets: ${{ secrets.PYPI_PASSWORD }}

  deploy-to-radix:
    needs: publish-latest-docker-image
    uses: ./.github/workflows/radix-deploy.yml
    with:
      radix-environment: dev
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}