on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  run-tests:
    uses: ./.github/workflows/testing.yml
