on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  run-tests:
    uses: ./.github/workflows/testing.yml

    #TODO REMOVE!
  radix-deploy:
    uses: ./.github/workflows/radix-deploy.yml
    with:
      radix-environment: 'dev'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}