on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  run-tests:
    uses: ./.github/workflows/testing.yml

  publish-docker-image:
    needs: [checks, run-tests]
    uses: ./.github/workflows/publish.yml
    with:
      image-tag: production
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  publish-new-pypi-package:
    needs: [checks, run-tests]
    uses: ./.github/workflows/publish-to-pypi.yml
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  radix-deploy:
    needs: publish-docker-image
    uses: ./.github/workflows/radix-deploy.yml
    with:
      radix-environment: 'prod'
    secrets:
      APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}
