on:
  workflow_dispatch:
  workflow_call: # Workflow is meant to be called from another workflow, with the image tag as input
    inputs:
      image-tags:
        description: "Which tag to give the images. Supports multiple tags if comma separated, ie 'tag1,tag2'"
        default: "latest"
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

env:
  DOCKER_IMAGE: datamodelingtool.azurecr.io/dmss
  IMAGE_REGISTRY: datamodelingtool.azurecr.io
  REGISTRY_USER: datamodelingtool

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: "Write version file"
        run: echo $(git log -n 1 --format=format:'%C(yellow)%h% %C(blue)%>(12) %cs %C(green)%>(12,mtrunc)%aN%C(auto,reset)  %s%C(auto) %D') > src/version.txt

      - name: "Docker Login"
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.IMAGE_REGISTRY }} --password-stdin --username ${{ env.REGISTRY_USER }}

      - name: "Build Docker image"
        run: docker build --tag ${DOCKER_IMAGE} .

      - name: "Tag and push"
        run: |
          echo "Tagging with ${{ inputs.image-tags }}"
          IFS=','
          for IMAGE_TAG in $(echo ${{ inputs.image-tags }})
          do
            echo "Tagging with $IMAGE_TAG"
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$IMAGE_TAG
            docker push $DOCKER_IMAGE:$IMAGE_TAG
          done

      - name: "Docker Logout"
        run: docker logout
