on:
  workflow_dispatch:
  workflow_call:  # Workflow is meant to be called from another workflow, with the image tag as input
    inputs:
      image-tag:
        description: 'Which tag to set for the produced docker images'
        default: 'latest'
        required: true
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true



env:
  DOCKER_IMAGE: datamodelingtool.azurecr.io/dmss
  IMAGE_REGISTRY: datamodelingtool.azurecr.io
  REGISTRY_USER: datamodelingtool

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: "Write version file"
        run: echo $(git log -n 1 --format=format:'%C(yellow)%h% %C(blue)%>(12) %cs %C(green)%>(12,mtrunc)%aN%C(auto,reset)  %s%C(auto) %D') > src/version.txt
      - name: "Build Docker image"
        run: docker build --tag ${DOCKER_IMAGE}:${{ inputs.image-tag }} .
      - name: "Docker Login"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ${{ env.IMAGE_REGISTRY }} --password-stdin --username ${{ env.REGISTRY_USER }}
      - name: "Push Docker image"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: docker push ${DOCKER_IMAGE}:${{ inputs.image-tag }}
      - name: "Determine tag"
        if: "startsWith(github.ref, 'refs/tags/')"
        id: "determine-tag"
        run: "echo \"::set-output name=tag::${GITHUB_REF#refs/tags/}\""
      - name: "Tag Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: docker tag ${{ env.DOCKER_IMAGE }}:${{ inputs.image-tag }} ${{ env.DOCKER_IMAGE }}:${{ steps.determine-tag.outputs.tag }}
      - name: "Push Docker image (versioned)"
        if: "startsWith(github.ref, 'refs/tags/')"
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ steps.determine-tag.outputs.tag }}
      - name: "Docker Logout"
        if: "'refs/heads/master' == github.ref || startsWith(github.ref, 'refs/tags/')"
        run: docker logout
