on:
  workflow_dispatch:
  workflow_call:

jobs:
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Build Docker Images"
        run: docker-compose -f docker-compose.yml  -f docker-compose.ci.yml build
      - name: "BDD Tests"
        run: docker-compose -f docker-compose.yml  -f docker-compose.ci.yml run dmss behave -e OAUTH_CLIENT_SECRET=123
      - name: "Unit Tests"
        run: docker-compose -f docker-compose.yml  -f docker-compose.ci.yml run dmss pytest -e OAUTH_CLIENT_SECRET=123
